name: meeting_rooms
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  equatable: ^2.0.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.2
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^5.2.1
  googleapis: ^7.0.0
  googleapis_auth: ^1.2.0
  intl: ^0.17.0
  url_launcher: ^6.0.12

dev_dependencies:
  bloc_test: ^8.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
