name: meeting_rooms
description: App to find a free meeting room.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^5.4.2
  googleapis: ^9.2.0
  googleapis_auth: ^1.2.0
  intl: ^0.17.0
  material_design_icons_flutter: ^6.0.7096
  url_launcher: ^6.0.13

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
