name: meeting_rooms
description: App to find a free meeting room.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  equatable: ^2.0.3
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^5.2.1
  googleapis: ^7.0.0
  googleapis_auth: ^1.2.0
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6295
  url_launcher: ^6.0.13

dev_dependencies:
  bloc_test: ^8.5.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
