export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_FAILED = 'ROOMS_FAILED';
export const ADD_ROOMS = 'ADD_ROOMS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';